02/March/2026

In [ ]:
# Introduction to Numpy
# Numpy ---> Num(Numerical)+py(phython)

# This is an open-source liberary of python and this is used for scientific calculations.
# List is hetrogenous data type and numpy is homogenous data type.


In [1]:
import numpy as np

In [ ]:
a=[1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
a=np.array([1,2,3])
a*3

array([3, 6, 9])

In [ ]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [ ]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a=[[1,2,3],[4,5,6,],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Row =3, r1=[1,2,3], r2=[4,5,6], r3=[7,8,9]
# column=3, c1=[1,4,7], c2=[2,5,8], c3=[3,6,9]

In [ ]:
print("Total Shape", b.shape)  ### shape=row, column
print("Total Elements", b.size)  ###size=row*column
print("Total Dimensions", b.ndim) ###total dimension=2

Total Shape (3, 3)
Total Elements 9
Total Dimensions 2


In [ ]:
# pre-built functions of Numpy

In [ ]:
# (1). zeroes() ---> It will create an array in which all the values will be 0 in either
# one dimensional or multi-dimensional

In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones() ---> It will return an array in which all the values are 1 in either
# one dimension or multi-dimension.

In [ ]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Array ---> 5,6 row and column  print it's dimensions and total elements
a=np.ones((5,6))
print(a)
print("Total Elements", a.size)
print("Total Dimension", a.ndim)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Total Elements 30
Total Dimension 2


5/March/2026

(3). eye ---> It will creat an array in which digonal positional element are 1 and rest all are 0.

In [ ]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

(4). diag() --> it will set our custm value on digonal position.

In [ ]:
a=np.array([1,45,78,90])
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

(5). Randam Moudle
- (a). Randint() ---> It will creat random number in a given range.
- sytax.: np.random.randint(min_range,max_range,total_number)

In [ ]:
a= np.random.randint(1,10,3)
a

array([6, 8, 1])

(b). Rand() --> It will creat random number in range 0-1.

In [ ]:
a=np.random.rand(5)
a

array([0.63482739, 0.60083016, 0.20839773, 0.13733349, 0.72466924])

(c). seed() --> It will fix our random generated data.

In [ ]:
np.random.seed(3)
a=np.random.randint(1,10,3)
a

array([9, 4, 9])

- View vs copy
- - view means modification in original data copy means changes in duplicate data will not reflect the original data.

In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
a[3:6]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
#b[::]=0
b


array([40, 50, 60])

In [ ]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

- Operation o Array
- -(1). arange()--> it will work as for loop in numpy

In [ ]:
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b=a>10

a[b]

array([11, 12, 13, 14, 15])

In [ ]:
b=a%2==0
a[b]

array([ 2,  4,  6,  8, 10, 12, 14])

- Reshaping Condition
- -n(row) * n(column)=n(total_element)

-- ex. total element=12
- 1*12,12*1,3*4,4*3....

In [ ]:
a= np.random.randint(1,50,12)
a

array([11, 39, 37,  3, 11,  1, 13,  5, 13, 45, 36, 33])

In [ ]:
np.random.randint(1,50,12).reshape(3,4)

array([[26, 22, 34, 17],
       [10,  4,  7, 23],
       [17, 29, 13, 33]])

In [ ]:
a.reshape(2,6)

array([[ 9,  1, 22, 20, 11, 44],
       [42, 11, 22, 39, 33, 21]])

In [ ]:
a.reshape(3,4)

array([[ 9,  1, 22, 20],
       [11, 44, 42, 11],
       [22, 39, 33, 21]])

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b ## not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b) #matrix multiplication

array([[19, 22],
       [43, 50]])

- 06/03/2026

In [ ]:
a=np.arange(1,4)
a

array([1, 2, 3])

In [ ]:
a**2

array([1, 4, 9])

In [ ]:
a**3

array([ 1,  8, 27])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# LinSapce() --> It will return same gap value in a given range.

In [ ]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

unique()--> It will return 3 array.
-  arr--> return original value of array.

- return_index = True --> return index value of unique

- return_counts = True --> return count of unique value(frequancy)

In [ ]:
a=np.array([1,2,2,2,2,3,4,3,4,5,6,4,5,9])
np.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 9]),
 array([ 0,  1,  5,  6,  9, 10, 13]),
 array([1, 4, 2, 3, 2, 1, 1]))

hstack vs Vstack
- hstack --> It will add 2 or more array in horizontally.
- Vstack --> It will add 2 or more array in vertically.

In [ ]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
c=np.arange(21,30).reshape(3,3)

In [ ]:
np.hstack((a,b,c))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

- q. array(30,80) total element=36 --> reshape(2*18,4*9,6*6)

In [ ]:
np.random.randint(30,80,36).reshape(2,18)


array([[77, 43, 32, 75, 78, 39, 46, 55, 79, 43, 72, 38, 70, 38, 40, 53,
        51, 45],
       [55, 46, 60, 70, 34, 58, 73, 76, 36, 63, 67, 66, 54, 39, 55, 45,
        76, 35]])

In [ ]:
np.random.randint(30,80,36).reshape(4,9)

array([[66, 45, 31, 69, 74, 44, 42, 47, 44],
       [79, 67, 33, 36, 41, 44, 36, 68, 43],
       [53, 64, 70, 63, 54, 32, 76, 77, 44],
       [44, 39, 50, 65, 49, 33, 44, 51, 34]])

In [ ]:
np.random.randint(30,80,36).reshape(6,6)

array([[75, 62, 37, 41, 67, 72],
       [43, 58, 64, 67, 54, 48],
       [49, 72, 64, 37, 67, 44],
       [40, 56, 47, 70, 30, 48],
       [53, 66, 51, 62, 76, 79],
       [60, 46, 64, 46, 75, 44]])

In [ ]:
a= np.arange(6,10)
b=np.arange(11,15)

In [ ]:
np.hstack((a,b))

array([ 6,  7,  8,  9, 11, 12, 13, 14])