(1). Write statement to import numpy?

In [1]:
import numpy as np

(2). Create an array using numpy?

In [2]:
np.array([1,2,3])

array([1, 2, 3])

(3). Create an array of 10 random integers?

In [3]:
np.random.randint(1,11,10)

array([ 9,  3,  7,  5, 10,  5,  3,  7,  3,  2])

(4). Create an array which contains value 5, 10 times?

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

(5). Create an array of elements from 10-20?

In [7]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

(6). Create a one dimensional array and convert that into 3*3 matrix?

In [8]:
a=np.arange(10,19,1)
b=a.reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

(7). Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?

In [9]:
a=np.random.rand(9).reshape(3,3)
a


array([[0.77657556, 0.61968911, 0.20037105],
       [0.04744572, 0.56285674, 0.47375928],
       [0.44046945, 0.83916584, 0.08490067]])

(8). Concatenate 2D array horizontally and vertically ?

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [11]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [12]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])