In [2]:
import numpy as np

 - 1. whats is difference b/w list and array.
 - 2. create an a array shap and size, digonal?

 - 3. zeros onse,eys ,dig ,linsapce

 - 4 what is hstack and vstack explain code with wxample?
 - 5 what is view vs copy show example?
 - 6 we have create 2 matrix ,metrix maltippl
 - 7 we have create an array 1 to 10 ,then you have shape 3*3 matrix then profome total sum,row by sum,col by sum
 - 8 what is random interger rand,seek explain with example code.

In [ ]:
#solution

q1. list-> list is hetrogenous and multiple data type use

array -> array is  homogenous and single data type use (numerical)

q2.

In [19]:
a=np.array([[1,2,3,4],[6,6,7,8]])
print(a)
print("a shap",a.shape)
print("a dimension",a.ndim)
print("a size",a.size)

[[1 2 3 4]
 [6 6 7 8]]
a shap (2, 4)
a dimension 2
a size 8


q3.

zeros array => array all element 0.

once array => array all element 1.

eye array => digonal element is 1 and other 0.

diag array => without digonal element is zero .

linspace=> same gap value return




In [9]:
a=np.zeros(3)
a


array([0., 0., 0.])

In [10]:
a=np.ones(3)
a

array([1., 1., 1.])

In [12]:
a=np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [14]:
a=np.diag(np.array([1,2,3,4]))
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
a=np.linspace(1,5,4)
a

array([1.        , 2.33333333, 3.66666667, 5.        ])

q4.

hstack => add 2 and more array horizontal

vstack => add 2 and more array vartical

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

q5.
view= view in  change data,then change origanal data and refalect duplicate data

copy= copy in change data, then not change orignal data

In [20]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#view
a[3:6]=0
a

array([1, 2, 3, 0, 0, 0, 7])

In [25]:
#copy
a=np.array([1,2,3,4,5,6,7])
b=a[3:6].copy()
print("after change b data:",b)
b=0
print(a)
print("copy then change data:",b)


after change b data: [4 5 6]
[1 2 3 4 5 6 7]
copy then change data: 0


q6.


In [31]:
a=np.array([[1,2],[4,5]])
b=np.array([[1,2],[4,5]])
c=a.dot(b)
c

array([[ 9, 12],
       [24, 33]])

q7.

In [32]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
b=np.sum(a)
b

np.int64(45)

In [34]:
c=np.sum(a,axis=1) # row by sum
c

array([ 6, 15, 24])

In [35]:
d=np.sum(a,axis=0) # col by sum
d

array([12, 15, 18])

q8.
randome => randam is modul
 - randint=> fix range randam number, kitne number chaiye
 - rand => 0 to 1 range ,divied need part
 - seed => fix randam generated data

In [27]:
a=np.random.randint(1,10,2)
a

array([9, 4])

In [28]:
a=np.random.rand(2)
a

array([0.0052646 , 0.34077837])

In [29]:
np.random.seed(3)
a=np.random.randint(1,10,2)
a

array([9, 4])